# it should be renamed to config.yaml
OpenAI:
  model: "gpt-4o"
  api_version: ''
  api_key: ''
  api_base: ''
AliOSS:
  AccessKey_ID: ''
  AccessKey_Secret: ''
  bucket_name: ''
testImageUrl:
  testImageUrl: ''